# Generated by Django 6.0 on 2025-12-08 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resource',
            name='Resource_Type',
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='resource',
            name='resource_type',
            field=models.CharField(choices=[('Lab', 'Lab'), ('Seminar Hall', 'Seminar Hall'), ('Equipment', 'Equipment')], default='Lab', max_length=20),
            preserve_default=False,
        ),
    ]
